### PR TITLE
[#1] Undefined written if no example is returned by API Fix

### LINKED ISSUE #1: Undefined written if no example is returned by API
**Current Scenario**
Currently, there is no checking done regarding whether an example is present in the API response or not.
It is assumed that the example is always present.
If the example is not present 'undefined' is written in the file (as the data is undefined in JSON response).

**Expected Scenario**
It should be checked whether example is present or not in the JSON response.
if it is not, do not write ```ex: undefined``` in the file. 

Most pertains to [this line](https://github.com/ashawe/Word-Meanings-to-Markdown/blob/master/index.js#L56)

### PR DESCRIPTION
**Pull request by saraogipraveen**
Fixes #1

Presence check added for `definition.example`, It will be written to file only if it exits

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -53,7 +53,9 @@ function writeMeaningToFile(inputStream, filename) {
         toWrite += "    - " + meaning.partOfSpeech + "\n";
         meaning.definitions.forEach(definition => {
             toWrite += "        - " + definition.definition + "\n";
-            toWrite += "            - ex: " + definition.example + "\n";
+            if(definition.example){
```
Comment (saglaniharsh) [inline index.js]: please do a strict check for undefined (triple equals)

**Review by ashawe — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (saraogipraveen) [reply index.js]: @ashawe  done

**Review by ashawe — APPROVED** [review]
